"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, BrainCircuit, Cookie, Database, Eye, FileSearch, Globe2, Layers3, LockKeyhole, Radar, Scale, ShieldCheck, Sparkles } from "lucide-react";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Button, Card, Badge } from "@/components/ui";
import { PrivacyScore } from "@/components/privacy/privacy-score";

const capabilities=[
 {icon:FileSearch,title:"Inspect",text:"Surface observable privacy signals from digital services."},
 {icon:BrainCircuit,title:"Understand",text:"Turn complex privacy language into structured findings."},
 {icon:Layers3,title:"Compare",text:"Place declared practices beside technical evidence."},
 {icon:Scale,title:"Evaluate",text:"Contextualize findings across privacy frameworks."},
];
const regulations=[['🇨🇱','Chile','Ley 21.719'],['🇪🇺','European Union','GDPR'],['🇧🇷','Brazil','LGPD'],['🇺🇸','California','CCPA / CPRA']];

export default function LandingPage(){return <div className="min-h-screen overflow-x-hidden"><Navbar/><main><section className="relative overflow-hidden border-b border-subtle"><div className="absolute inset-0 privacy-grid opacity-70"/><div className="absolute left-1/2 top-0 h-[520px] w-[760px] -translate-x-1/2 rounded-full bg-privacy-cyan/10 blur-[110px]"/><div className="relative mx-auto grid min-h-[calc(100vh-64px)] max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div><div className="mb-6 flex items-center gap-2"><Badge tone="info"><Sparkles className="h-3.5 w-3.5"/> Privacy intelligence</Badge><span className="text-xs text-muted">Evidence-first</span></div><h1 className="max-w-4xl font-display text-5xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-6xl lg:text-7xl">See what your <span className="bg-gradient-to-r from-privacy-cyan via-privacy-blue to-privacy-violet bg-clip-text text-transparent">digital life</span> reveals.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted sm:text-lg">PRIVACYOS analyzes digital services, uncovers data practices and transforms privacy evidence into actionable intelligence.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard/scanner"><Button size="lg">Analyze a service <ArrowRight className="h-4 w-4"/></Button></Link><Link href="/dashboard"><Button variant="secondary" size="lg">Explore demo</Button></Link></div><div className="mt-9 flex flex-wrap gap-5 text-xs text-muted"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-privacy-cyan"/> Explainable scoring</span><span className="flex items-center gap-2"><Radar className="h-4 w-4 text-privacy-blue"/> Observable evidence</span></div></div><HeroVisual/></div></section>
<section id="product" className="border-b border-subtle py-5"><div className="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-8 gap-y-3 px-5 text-xs font-medium text-muted sm:px-8"><span>Privacy intelligence</span><span>Evidence-based analysis</span><span>Explainable scoring</span><span>Multi-jurisdiction</span></div></section>
<section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><SectionIntro eyebrow="THE PROBLEM" title="Privacy is invisible by design." text="Policies are dense, trackers are quiet, and regulatory context is fragmented. PRIVACYOS makes those signals easier to inspect."/><div className="mt-12 grid gap-4 md:grid-cols-3">{[{icon:FileSearch,title:"Policies are complex",text:"Important data practices can be buried inside long legal documents."},{icon:Cookie,title:"Tracking is hidden",text:"Cookies and third-party technologies can operate beyond the obvious interface."},{icon:Globe2,title:"Regulations are fragmented",text:"The relevance of a finding changes with jurisdiction and context."}].map((x,i)=><motion.div initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} key={x.title}><Card className="h-full p-6"><div className="grid h-11 w-11 place-items-center rounded-xl bg-privacy-cyan/10 text-privacy-cyan"><x.icon className="h-5 w-5"/></div><h3 className="mt-6 font-display text-xl font-semibold">{x.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{x.text}</p></Card></motion.div>)}</div></section>
<section id="how-it-works" className="border-y border-subtle surface"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><SectionIntro eyebrow="HOW IT WORKS" title="From a URL to a privacy intelligence layer." text="The experience follows the same modular pipeline that will power the real analysis engine."/><div className="mt-12 grid gap-3 md:grid-cols-4">{['Enter','Inspect','Understand','Score'].map((x,i)=><div key={x} className="relative rounded-2xl border border-subtle surface-2 p-5"><span className="font-display text-sm text-privacy-cyan">0{i+1}</span><h3 className="mt-8 font-display text-xl font-semibold">{x}</h3><p className="mt-2 text-sm text-muted">{['Add a digital service to inspect.','Collect observable privacy signals.','Structure practices and context.','Turn findings into an explainable result.'][i]}</p>{i<3&&<ArrowRight className="absolute right-5 top-1/2 hidden h-4 w-4 -translate-y-1/2 text-muted md:block"/>}</div>)}</div></div></section>
<section className="relative overflow-hidden"><div className="absolute inset-0 bg-privacy-radial"/><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.75fr_1.25fr] lg:py-32"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-privacy-cyan">PRIVACY SCORE</p><h2 className="mt-4 max-w-lg font-display text-4xl font-semibold tracking-tight sm:text-5xl">A number is useful when you can explain it.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-muted">The final score is designed to be reproducible. Each dimension maps to observable signals and documented methodology rather than a random model output.</p><Link href="/dashboard/analyses/demo-001" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-privacy-cyan">Explore a demo result <ArrowRight className="h-4 w-4"/></Link></div><Card className="p-6 sm:p-8"><div className="grid gap-8 md:grid-cols-[.75fr_1.25fr] md:items-center"><PrivacyScore score={78}/><div className="space-y-4">{[['Security',91],['Transparency',82],['Data Minimization',74],['Retention',61],['Tracking',54]].map(([label,value])=><div key={String(label)}><div className="mb-1.5 flex justify-between text-xs"><span className="text-muted">{label}</span><span className="font-medium">{value}</span></div><div className="h-1.5 rounded-full surface-3"><div className="h-full rounded-full bg-gradient-to-r from-privacy-cyan to-privacy-blue" style={{width:`${value}%`}}/></div></div>)}</div></div></Card></div></section>
<section id="methodology" className="surface border-y border-subtle"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><SectionIntro eyebrow="INTELLIGENCE LAYERS" title="Observe. Understand. Compare. Evaluate."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{capabilities.map((c,i)=><motion.div key={c.title} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}}><Card className="h-full p-6"><c.icon className="h-6 w-6 text-privacy-cyan"/><h3 className="mt-7 font-display text-xl font-semibold">{c.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{c.text}</p></Card></motion.div>)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><SectionIntro eyebrow="DECLARATION VS EVIDENCE" title="What is declared. What is observable. What needs review." text="PRIVACYOS is designed to make differences visible without turning them into automatic legal conclusions."/><div className="mt-12 grid gap-4 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><Card className="p-6"><p className="text-xs font-semibold uppercase tracking-widest text-privacy-blue">Declaration</p><p className="mt-5 text-sm leading-7 text-muted">“Analytics cookies are used to improve the user experience.”</p></Card><div className="mx-auto grid h-10 w-10 place-items-center rounded-full border border-subtle surface-2 text-muted"><ArrowRight className="h-4 w-4 lg:rotate-0"/></div><Card className="p-6"><p className="text-xs font-semibold uppercase tracking-widest text-privacy-cyan">Evidence</p><div className="mt-5 space-y-2 text-sm"><div className="rounded-xl surface-2 p-3">Google Analytics</div><div className="rounded-xl surface-2 p-3">Meta Pixel</div><div className="rounded-xl surface-2 p-3">Third-party analytics cookie</div></div><div className="mt-5 rounded-xl border border-risk-medium/20 bg-risk-medium/5 p-3 text-xs text-risk-medium">⚠ Potential inconsistency · Requires review</div></Card></div></section>
<section className="border-y border-subtle surface"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><SectionIntro eyebrow="REGULATORY INTELLIGENCE" title="Context changes the meaning of a finding." text="PRIVACYOS is designed to support multiple regulatory frameworks without hard-coding legal rules into the interface."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{regulations.map(([flag,name,reg])=><Card key={name} interactive className="p-5"><span className="text-2xl">{flag}</span><h3 className="mt-5 font-display text-lg font-semibold">{name}</h3><p className="mt-1 text-sm text-muted">{reg}</p></Card>)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="grid gap-4 md:grid-cols-2"><Audience title="For individuals" icon={Eye} text="Understand what digital services may collect and which privacy signals deserve attention."/><Audience title="For businesses" icon={Database} text="Turn privacy signals into a structured review workflow for products and digital services."/></div><div className="mt-4 rounded-3xl border border-subtle surface-2 p-7 sm:p-10"><div className="grid gap-8 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-privacy-violet">TECHNOLOGY</p><h2 className="mt-4 font-display text-3xl font-semibold">Built as a modular intelligence pipeline.</h2><p className="mt-4 text-sm leading-7 text-muted">Scanner, AI, regulatory context, risk logic and scoring remain separate so each layer can evolve without turning the product into a monolith.</p></div><div className="grid grid-cols-2 gap-3">{['Scanner','AI Engine','Regulatory','Risk Engine'].map((x,i)=><div key={x} className="rounded-2xl border border-subtle surface p-4"><div className="mb-5 text-xs text-muted">0{i+1}</div><p className="text-sm font-semibold">{x}</p></div>)}</div></div></div></section>
<section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-3xl border border-privacy-cyan/15 bg-[radial-gradient(circle_at_50%_0%,rgba(25,211,197,.13),transparent_55%)] surface p-8 text-center sm:p-14"><LockKeyhole className="mx-auto h-7 w-7 text-privacy-cyan"/><h2 className="mx-auto mt-5 max-w-2xl font-display text-4xl font-semibold tracking-tight sm:text-5xl">Privacy shouldn't be a black box.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-muted">Start with a controlled demo and explore the intelligence layer.</p><Link href="/dashboard/scanner" className="mt-7 inline-block"><Button size="lg">Analyze a service <ArrowRight className="h-4 w-4"/></Button></Link></div></section></main><Footer/></div>}

function HeroVisual(){return <motion.div initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{duration:.7}} className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 rounded-[40px] bg-gradient-to-r from-privacy-cyan/10 via-privacy-blue/5 to-privacy-violet/10 blur-3xl"/><Card className="relative overflow-hidden p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-muted">Privacy analysis</p><p className="mt-1 text-sm font-semibold">example.com</p></div><Badge tone="success">GOOD</Badge></div><div className="my-8 grid grid-cols-[.8fr_1.2fr] items-center gap-6"><PrivacyScore score={82} size="sm"/><div className="space-y-4">{[['Security',91],['Transparency',82],['Tracking',64],['Third Parties',72]].map(([label,value])=><div key={String(label)}><div className="mb-1.5 flex justify-between text-xs"><span className="text-muted">{label}</span><span>{value}</span></div><div className="h-1.5 rounded-full surface-3"><div className="h-full rounded-full bg-gradient-to-r from-privacy-cyan to-privacy-blue" style={{width:`${value}%`}}/></div></div>)}</div></div><div className="grid grid-cols-3 gap-2 text-center text-[11px]"><div className="rounded-xl surface-2 p-3"><p className="text-muted">Trackers</p><p className="mt-1 font-semibold">7</p></div><div className="rounded-xl surface-2 p-3"><p className="text-muted">Risks</p><p className="mt-1 font-semibold">3</p></div><div className="rounded-xl surface-2 p-3"><p className="text-muted">Evidence</p><p className="mt-1 font-semibold">18</p></div></div></Card><div className="absolute -bottom-5 -left-5 rounded-2xl border border-subtle surface p-3 shadow-card"><div className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full bg-risk-low"/> Evidence collected</div></div></motion.div>}
function SectionIntro({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-privacy-cyan">{eyebrow}</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">{title}</h2>{text&&<p className="mt-5 text-sm leading-7 text-muted sm:text-base">{text}</p>}</div>}
function Audience({title,icon:Icon,text}:{title:string;icon:React.ElementType;text:string}){return <Card className="p-7 sm:p-9"><Icon className="h-6 w-6 text-privacy-cyan"/><h2 className="mt-8 font-display text-2xl font-semibold">{title}</h2><p className="mt-3 max-w-lg text-sm leading-7 text-muted">{text}</p><Link href="/dashboard/scanner" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-privacy-cyan">Explore <ArrowRight className="h-4 w-4"/></Link></Card>}
