"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Logo } from "@/components/layout/logo";
import { ThemeToggle } from "@/components/layout/theme-toggle";
import { Button, Input, Alert } from "@/components/ui";
export default function LoginPage(){const router=useRouter();const [submitted,setSubmitted]=useState(false);const submit=(e:React.FormEvent)=>{e.preventDefault();setSubmitted(true);setTimeout(()=>router.push("/dashboard"),500)};return <div className="min-h-screen bg-[var(--privacy-void)]"><header className="flex h-16 items-center justify-between border-b border-subtle px-5 sm:px-8"><Logo/><ThemeToggle/></header><main className="grid min-h-[calc(100vh-64px)] place-items-center px-5 py-12"><div className="w-full max-w-md"><div className="mb-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-privacy-cyan/10 text-privacy-cyan"><ShieldCheck className="h-6 w-6"/></div><h1 className="mt-5 font-display text-3xl font-semibold">Welcome back</h1><p className="mt-2 text-sm text-muted">Sign in to your privacy workspace.</p></div><form onSubmit={submit} className="surface rounded-2xl border border-subtle p-6 shadow-card sm:p-8"><div className="space-y-5"><Input label="Email" type="email" placeholder="you@example.com" required/><Input label="Password" type="password" placeholder="••••••••" required minLength={6}/><Button className="w-full" size="lg" disabled={submitted}>{submitted?"Opening demo workspace…":<>Sign in <ArrowRight className="h-4 w-4"/></>}</Button></div>{submitted&&<div className="mt-4"><Alert tone="info" title="Mock authentication">This Foundation build uses client-side demo navigation only.</Alert></div>}<div className="mt-6 text-center text-sm text-muted">New to PRIVACYOS? <Link href="/register" className="font-medium text-privacy-cyan">Create account</Link></div><div className="mt-3 text-center"><Link href="/dashboard" className="text-xs text-muted hover:text-[var(--privacy-text)]">Try Demo →</Link></div></form></div></main></div>}
