"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Logo } from "@/components/layout/logo";
import { ThemeToggle } from "@/components/layout/theme-toggle";
import { Button, Input, Alert } from "@/components/ui";
export default function RegisterPage(){const router=useRouter();const [error,setError]=useState("");const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(fd.get("password")!==fd.get("confirm")){setError("Passwords do not match.");return}setError("");router.push("/dashboard")};return <div className="min-h-screen bg-[var(--privacy-void)]"><header className="flex h-16 items-center justify-between border-b border-subtle px-5 sm:px-8"><Logo/><ThemeToggle/></header><main className="grid min-h-[calc(100vh-64px)] place-items-center px-5 py-12"><div className="w-full max-w-md"><div className="mb-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-privacy-cyan/10 text-privacy-cyan"><ShieldCheck className="h-6 w-6"/></div><h1 className="mt-5 font-display text-3xl font-semibold">Create your workspace</h1><p className="mt-2 text-sm text-muted">Start exploring privacy intelligence.</p></div><form onSubmit={submit} className="surface rounded-2xl border border-subtle p-6 shadow-card sm:p-8"><div className="space-y-5"><Input label="Name" name="name" placeholder="Your name" required/><Input label="Email" name="email" type="email" placeholder="you@example.com" required/><Input label="Password" name="password" type="password" placeholder="At least 6 characters" minLength={6} required/><Input label="Confirm password" name="confirm" type="password" placeholder="Repeat password" minLength={6} required/>{error&&<Alert tone="error" title="Check your details">{error}</Alert>}<Button className="w-full" size="lg">Create account <ArrowRight className="h-4 w-4"/></Button></div><div className="mt-6 text-center text-sm text-muted">Already have an account? <Link href="/login" className="font-medium text-privacy-cyan">Sign in</Link></div></form></div></main></div>}
